# Generated by Django 5.2 on 2025-05-01 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_seat_count', models.PositiveIntegerField(blank=True, null=True)),
                ('economy_seat_count', models.PositiveIntegerField()),
                ('seat_count_total', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Business', 'Business'), ('Economy', 'Economy')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_fee', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('from_location', models.CharField(choices=[('Port Harcourt', 'Port Harcourt'), ('Abuja', 'Abuja'), ('Lagos', 'Lagos'), ('Owerri', 'Owerri'), ('Kano', 'Kano')], max_length=100)),
                ('to_location', models.CharField(choices=[('Port Harcourt', 'Port Harcourt'), ('Abuja', 'Abuja'), ('Lagos', 'Lagos'), ('Owerri', 'Owerri'), ('Kano', 'Kano')], max_length=100)),
                ('eta', models.CharField(choices=[('30m', '30m'), ('45m', '45m'), ('1h', '1h'), ('1h 15m', '1h 15m'), ('1h 30m', '1h 30m'), ('2h', '2h')], max_length=50)),
                ('max_baggage_weight', models.PositiveIntegerField(default=20)),
                ('amount', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.airplane')),
                ('select_travel_class', models.ManyToManyField(to='booking.travelclass')),
            ],
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('unique_id', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('total_amount', models.PositiveIntegerField()),
                ('flight_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.flightschedule')),
                ('select_travel_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.travelclass')),
            ],
        ),
    ]
