# Generated by Django 5.2 on 2025-05-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='business_seat_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
